### ISSUE TITLE
Sources of the english_??_topics collections

### ISSUE THREAD

**Issue by l3kn** [ckoshka/langwitch-deno#1]
Hi ckoshka,

Thanks for working such an extensive language learning resource!

I've sampled a few of the sentence files uploaded on archive.org
and the ones centered on specific topics seem very interesting.

Looking through some of your code I could not figure out where they were gathered from
and how the topics were determined, can you provide some information on this?

**Comment by ckoshka** [comment]
The topics: I just picked everything I could think of, and took requests from people on Discord. 

The process: this varied depending on the topic, but the central part of the pipeline was: 1) gather a corpus of documents that seem relevant to the topic (Wikipedia articles, mostly – scihub and arxiv papers proved too annoying to parse in most cases, but their abstracts were helpful) 2) start with an unrelated English sentence that is around 12-15 words long 2) use LDA or `paraphrase-MiniLM-L3-v2` (or in simple cases, just TF-IDF) to remove the most irrelevant spans of text (lowest cosine similarity, weighted against renyi entropy) 3) pass the partially-blanked-out sentence to BART 4) sample at a relatively high temperature initially, but decrease once it starts becoming relevant 5) do this repeatedly for a few thousand sentences until you have something decently sized. 

I mainly did this to test the proficiency of Google's translation engines across different disciplines; the idea was to understand the limitations of their training data, etc. But when I showed it to other people they said "oh, that's great! now I can learn sentences in something I'm interested in" so I decided to upload all of the data I accumulated.

**Comment by l3kn** [comment]
Thanks for the detailed and quick response!

I'll have read up on the ML technology you described and then figure out how that could be used to improve my current learning setup (working through texts in the target language in chunks of a few sentences, learning all relevant words involved, then translating by hand and comparing that with a computer translation).

It should also be possible to use your collection combined with lemmatization and a list of known words to slowly introduce new sentences with a few unknown words into a spaced repetition system.
